[project]
name = "zeppfit"
version = "0.1.0"
description = "A Python script, which allows users to export workout data from Mi Fit and Zepp applications"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fit-tool>=0.9.13",
    "furl>=2.1.4",
    "geopandas>=1.0.1",
    "gpxpy>=1.6.2",
    "install-playwright>=0.1.0",
    "marimo>=0.15.2",
    "pandas>=2.2.3",
    "playwright>=1.51.0",
    "pydantic>=2.10.6",
    "python-dotenv>=1.1.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "pyright>=1.1.397",
    "ruff>=0.11.2",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"


[tool.uv.sources]
zeppfit = { path = "src" }
